### ISSUE TITLE
Initial color not set

### ISSUE THREAD

**Issue by TomDeSmet** [alecritson/craft-spectrum-fieldtype#6]
I noticed that when there's no color chosen, the spectrum field has black as its default color. But as long as the user does not explicitely set a color (because they fancy the default black) in the template, there's no output.

It's not that big of a deal, but it doesn't provide nice code because I'm not sure how to test on it.
Is not empty, not fieldName, != "null", |length
nothing seems to work.

**Comment by alecritson** [comment]
Hey @TomDeSmet 

Thanks for the heads up, I understand this would have been frustrating.

Now you can set a default color in the fieldtype settings, this will replace the initial black when first creating an entry etc, otherwise it will still default to black but will actually output `#000000` in your template.

Hope that helps :)

FYI it turns out you could have tested it like `{{ fieldName == ''  ? 'no color' : 'color' }}` but thats not pretty or relevant now...
